### ISSUE TITLE
Add new DoneJS command to print generator version

### ISSUE THREAD

**Issue by leoj3n** [donejs/developer-relations#24]
Right now in the [generator-donejs ISSUE_TEMPLATE.md](https://github.com/donejs/generator-donejs/blob/054a1c9aef71e4063c840abde13780e338474b48/.github/ISSUE_TEMPLATE.md) it asks for `generator-donejs version` but there is no convenient way to print this out.

Therefore I suggest we add a command to DoneJS that is the equivalent of what I do now to get that information:

```
cat node_modules/generator-donejs/package.json | grep '"version":'
```

Currently I'm not sure what the syntax of this command should be or in which repo the code for the command would need to live.

**Comment by phillipskevin** [comment]
`npm` also gives this information:
```
$ npm ls generator-donejs
place-my-order@0.10.0 /Users/kevin/dev/place-my-order
└── generator-donejs@1.0.0-alpha.27
```

**Comment by chasenlehara** [comment]
Replacing `generator-donejs version` with `npm ls generator-donejs` seems like the ideal solution to this issue.
