### ISSUE TITLE
Use nightmare instead of zombie?

### ISSUE THREAD

**Issue by leoj3n** [donejs/developer-relations#37]
Zombie docs are really lacking, making it hard to use, and it's not very robust (you can't take screenshots, is limited by jsdom). Maybe it's faster but getting up and running with it is slow.

Perhaps Nightmare might be a better alternative? It uses Electron and looks like it has more comprehensive docs.

https://github.com/segmentio/nightmare

**Comment by chasenlehara** [comment]
I’m not sure which project(s) this is related to; could you please file an issue in the repo(s) in which this is relevant?
