### ISSUE TITLE
CanJS GitHub example app design

### ISSUE THREAD

**Issue by chasenlehara** [donejs/developer-relations#39]
Design a UI for an app that:

- Has a form for creating a new issue (at least the title and description)
- Shows a list of GitHub issues (at least the title and first line of the description)
- Has controls for reordering the list of issues via drag & drop

I think the list will automatically save, so a separate save button isn’t required.

**Comment by chasenlehara** [comment]
Here’s a starter JS Bin: http://jsbin.com/safigic/11/edit?html,output

It uses Bootstrap right now, but it doesn’t have to. The verbiage is flexible too; we can give it a different title or rename the “Submit new issue” button to something shorter. It also doesn’t have any controls for reordering, so those need to be added.

**Comment by jamiemccue** [comment]
@chasenlehara 

Notes:
- on hover the row sort icon appears, you can then drag and drop the row
- after dropping the row the background color flashes a light green confirming the new drop location (optional)
- the read more/less link is simple as it seemed unnecessary to add excessive ui 
- the horizontal form inputs is super clean. could be a concern for adding a long description. let me know if you want me to mockup a form layout
- i'd be happy to discuss this version to make any improvements
- I added a row ID but you may not want them

![github-issues](https://cloud.githubusercontent.com/assets/381138/25717442/5550730c-30b7-11e7-9cf4-1c3ef30a5932.png)

![github-issues](https://cloud.githubusercontent.com/assets/381138/25717914/f4ea02ba-30b8-11e7-9b7a-99d3cd8dff36.png)

![github-issues-2](https://cloud.githubusercontent.com/assets/381138/25718035/7b21a27a-30b9-11e7-8049-5eae9ccae66f.png)

**Comment by chasenlehara** [comment]
This looks great, thank you! The only thing I would change is turning the description into a longer-form textarea for (potentially) multi-line input.

**Comment by jamiemccue** [comment]
@chasenlehara Thanks for the feedback. Here are a couple versions with a larger textarea:

![github-issues-textarea-horizontal](https://cloud.githubusercontent.com/assets/381138/25724933/8e51d644-30d2-11e7-9f32-7bc2341f36dd.png)
![github-issues-textarea-vertical-2](https://cloud.githubusercontent.com/assets/381138/25724934/8e52144c-30d2-11e7-9f3c-86d5bee8661b.png)
![github-issues-textarea-vertical](https://cloud.githubusercontent.com/assets/381138/25724935/8e52ca2c-30d2-11e7-84d7-c08289139724.png)

**Comment by jamiemccue** [comment]
@chasenlehara Do you require any more assistance on this issue? 

I was able to find my old bin: http://jsbin.com/komugexape/1/edit?html,css,output

**Comment by chasenlehara** [comment]
Looks great, thank you!
