### ISSUE TITLE
Prep the first survey’s launch

### ISSUE THREAD

**Issue by chasenlehara** [donejs/developer-relations#63]
We need to prepare to send out the first user survey in about a month. We’ll need to figure out:

- How we’ll collect emails for client developers and users on Gitter, the forums, etc.
- How we’ll advertise the survey on CanJS.com
- Which issues we will want to include for people to vote on
- How we’ll announce this new process on our blog
- What software we’ll use to manage this entire process
- Other things I haven’t thought about?

**Comment by bgando** [comment]
Here's my 2c:
1. How we’ll collect emails for client developers and users on Gitter, the forums, etc.
2. How we’ll advertise the survey on CanJS.com
- We can offer to send CanJS and DoneJS stickers to the first 50/100/whatever people who fill out our survey.
  - The survey will need to include an optional mailing address section as well as a toggle for if they want stickers sent to them.
- CanJS.com will have a pop-up that gets people excited and directs them to the survey
- For gitter/forums, we will send out notifications every day until we meet our desired # of responses.
3. Which issues we will want to include for people to vote on
As discussed in slack, Chasen will come up with the original list and whittle it down with the input of the rest of the team.
4. How we’ll announce this new process on our blog
- I think we should talk about how we have opportunities to get CanJS/DoneJS or even just JavaScript stickers for people who fill out our 6-week surveys.
5. What software we’ll use to manage this entire process
HubSpot has a Forms tool, but no native survey application. The best way to create and integrate surveys with HubSpot is to use the SurveyMonkey integration. In the past we have used the Forms tool, which we can export into a CMS. SurveyMonkey, however, has a lot more features and flexibility.
https://knowledge.hubspot.com/articles/kcs_article/forms/does-hubspot-have-a-tool-for-email-surveys
6. Other things I haven’t thought about?
We should make sure that the respondents get into our HubSpot CMS. They can do this automatically, we just need to make sure it is setup correctly.

**Comment by bgando** [comment]
### For the official process write-up I'll need:
- the official plan for gathering survey questions for the second round
- a copy of the first survey to use as an example
- a copy of the announcement blog to use as an example
- any other copy used on the website, gitter/forums/etc.
### The process doc will include:
- An example timeline/checklist
    - gathering questions
    - creating the survey
    - reviewing survey with the team, getting approval
    - setting up the website/notifications
    - any follow-up
    - collecting, analyzing, reporting data
- Process outline/HOWTO
    - gathering questions
    - creating the survey w/ Hubspot + survey monkey
    - reviewing survey with the team, getting approval
    - setting up the website/notifications
    - any follow-up needed
    - collecting, analyzing, reporting data
- example survey
- example blog and any other copy
- example meeting agenda for any required meetings

**Comment by chasenlehara** [comment]
Here are my current thoughts on the survey:

_How we’ll collect emails for client developers and users on Gitter, the forums, etc.:_

I’m going to look into creating a landing page we can have available all the time that will collect emails into HubSpot. We’ll then use HubSpot’s integration with SurveyMonkey to send the surveys to the emails we’ve collected.

_How we’ll advertise the survey on CanJS.com:_

I think we should show a bar across the bottom of our sites that links to the survey landing page. Additionally, we can integrate links to the survey landing page on pages where it makes the most sense.

_Which issues we will want to include for people to vote on:_

I have a WIP list here: https://gist.github.com/chasenlehara/826aa17e13376c9125277290536c983c

_How we’ll announce this new process on our blog:_

Here’s a WIP blog post: https://docs.google.com/a/jupiterjs.com/document/d/1C5iv_2ZbSOWrL0-vWClOYGq_HnFmaFhUO0G9RCmSLDA/edit?usp=sharing

_What software we’ll use to manage this entire process:_

Plan right now is to use HubSpot and SurveyMonkey.
